In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

In [ ]:
 # Create a length-10 integer array filled with zeros        
    np.zeros(10, dtype=int)


In [ ]:
 # Create a 3x5 floating-point array filled with 1s        
    np.ones((3, 5), dtype=float)

In [ ]:
 # Create a 3x5 array filled with 3.14        
    np.full((3, 5), 3.14)


In [ ]:
 # Create an array filled with a linear sequence        
# Starting at 0, ending at 20, stepping by 2
 np.arange(0, 20, 2)


In [ ]:
 # Create an array of five values evenly spaced between 0 and 1        
    np.linspace(0, 1, 5)

In [ ]:
# Create a 3x3 array of uniformly distributed       
# random values between 0 and 1        
np.random.random((3, 3))


In [ ]:
 # Create a 3x3 array of normally distributed random values        
    # with mean 0 and standard deviation 1        
    np.random.normal(0, 1, (3, 3))


In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)        
np.random.randint(0, 10, (3, 3))


In [ ]:
# Create a 3x3 identity matrix        
np.eye(3)


In [ ]:
# Create an uninitialized array of three integers        
# The values will be whatever happens to already exist at that memory location        
np.empty(3)

In [ ]:
 #ensure that the same random arrays are generated each time this code is run
    np.random.seed(0)

In [ ]:
Attributes of Array:
    ndim (the number of dimensions), 
    shape (the size of each dimension) 
    size (the total size of the array)
    itemsize (lists the size (in bytes) of each array element)
    nbytes (which lists the total size (in bytes) of the array)

In [ ]:
x[start:stop:step]
x[r_lb:r_ub , c_lb:c_ub : step]
x[::-1, ::-1]   --> rows and columns are reversed



In [ ]:
Accessing array rows and columns:
     print(x2[:, 0])  # first column of x2
    print(x2[0, :]) =  print(x2[0])
        

In [ ]:
# explicitly copy the data within an array or a subarray
 x_sub_copy = x[:2, :2].copy()

In [ ]:
# if you want to put the numbers 1 through 9 in a 3×3 grid, use reshape()
np.arange(1,10).reshape(3,3)

In [ ]:
# The conversion of a one-dimensional array into a two-dimensional row or column matrix done using
# reshape() or
# newaxis   x[np.newaxis,:]

In [ ]:
# Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines 
np.concatenate, np.vstack, and np.hstack
np.dstack --->stacks along third axis

In [ ]:
# The opposite of concatenation is splitting, which is implemented by the functions 
np.split, np.hsplit, and np.vsplit
np.dsplit --->splits along third axis

# Ufuncs

In [ ]:
np.add(), np.subtract(), np.multiply(), np.divide(), np.power(), np.mod()

In [ ]:
# It returns the absolute value of a number
np.abs()

In [ ]:
# Trigonometric, Iverse trigonometric, Exponential, Logarithmic
np.sin() ; np.arcsin() ; np.exp() ; np.log(), np.log2(), np.log10()
np.cos() ; np.arccos() ; [log1p(), expm1()] ---> Gives more precise values than raw exp and log
np.tan() ; np.arctan()

In [ ]:
# hyperbolic trig functions, bitwise arithmetic, 
# comparison operators, conversions from radians to degrees, rounding and remainders

In [ ]:
# It is useful to be able to specify the array where the result of the calculation will be stored, 
# rather tha creating temporary array, 'out' can be used to do that.
x = np.arange(5)        
y = np.empty(5)        
np.multiply(x, 10, out=y)        
print(y)


In [ ]:
# If we’d like to reduce an array with a particular operation, we can use the reduce method
x = np.arange(1,6)
np.multiply.reduce(x)

In [ ]:
# To store all the intermediate results of the computation, we can use accumulate
 np.add.accumulate(x)

#### NumPy’s universal functions can be used to vectorize operations

# Broadcasting

#### Another means of vectorizing operations is to use NumPy’s broadcasting functionality

#### Rules of broadcasting

##### • Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side. 



##### • Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape. 


##### • Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

# Boolean Arrays

In [ ]:
import numpy as np
x = np.random.randint(10, size=(3, 4)) 
x

#### To count the number of True entries in a Boolean array, np.count_nonzero 

In [ ]:
np.count_nonzero(x < 6)

## Masking

#### Now to select these values from the array, 
#### we can simply index on this Boolean array; this is known as a masking operation

In [ ]:
x[x < 5] ---> Masking

## and/or Versus &/| 

#### and and or gauge the truth or falsehood of entire object, 
#### while & and | refer to bits within each object. 

## Accessing and modifying arrays
#### simple indices (e.g., arr[0])
#### slices (e.g., arr[:5])
#### Boolean masks (e.g., arr[arr > 0]

# Fancy Indexing

#### We pass arrays of indices in place of single scalars

In [3]:
import numpy as np
x = np.random.randint(100, size=10)       
print(x)


[34 67  1 32 88 82  1 30 84 77]


In [4]:
[x[3],x[7],x[2]]

[32, 30, 1]

In [5]:
ind = [3, 7, 4]       
x[ind]


array([32, 30, 88])

In [6]:
ind = np.array([[3, 7],                       
                 [4, 5]])       
x[ind]


array([[32, 30],
       [88, 82]])

In [7]:
X = np.arange(12).reshape((3, 4))       
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
row = np.array([0, 1, 2])       
col = np.array([2, 1, 3])       
X[row, col]


array([ 2,  5, 11])

In [ ]:
 X[2, [2, 0, 1]]  #Combined indexing

### Modifying values with fancy indexing

In [ ]:
x = np.arange(10)        
i = np.array([2, 1, 8, 4])        
x[i] = 99        
print(x)

### Example

In [9]:
x = np.zeros(10)        
x[[0, 0]] = [4, 6]        
print(x)


[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Where did the 4 go? The result of this operation is to first assign x[0] = 4, followed by x[0] = 6. 
#### The result, of course, is that x[0] contains the value 6. 

# SORTING

### To return a sorted version of the array without modifying the input, you can use np.sort

In [ ]:
x = np.array([2, 1, 4, 3, 5])       
np.sort(x)


### By default np.sort uses an O [N log N] , quicksort algorithm

### If you prefer to sort the array in-place, you can instead use the sort method of arrays

In [ ]:
x.sort()       
print(x)


### A related function is argsort, which instead returns the INDICES of the sorted elements

In [ ]:
x = np.array([2, 1, 4, 3, 5])       
i = np.argsort(x)       
print(i)


### These indices can then be used (via fancy indexing) to construct the sorted array if desired

In [ ]:
x[i]

### Sorting along rows and columns can be done using "axis"

In [11]:
import numpy as np


In [18]:
x = np.array([37, 22, 53, 12, 46,55, 14])        
np.partition(x, 3)

array([12, 14, 22, 37, 46, 55, 53])

In [19]:
n = {}
n[(1,2,4)]=8
n[(4,2,1)]=10
n[(1,2)]=12
n

{(1, 2, 4): 8, (4, 2, 1): 10, (1, 2): 12}