# NUMPY

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape


(3, 5)

In [4]:
a.ndim #No of dimensions of the array

2

In [5]:
a.dtype.name #Describes the type of elements in an array

'int32'

In [7]:
a.itemsize #The size in bytes of each element of the array

4

In [9]:
a.size #The no of elements in an array

15

In [10]:
 type(a)

numpy.ndarray

In [11]:
a.data #The buffer containing the actual elements of array

# ARRAY CREATION

#### You can create an array from a regular Python list or tuple using the array function

In [19]:
a = np.array([1,2,3,4])    
a

array([1, 2, 3, 4])

In [20]:
a.dtype

dtype('int32')

#### Array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [21]:
a = np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### The type of the array can also be explicitly specified at creation time: as  c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [29]:
np.zeros(3)   #Creates an array full of zeros

array([0., 0., 0.])

#### By default, the dtype of the created array is float64.

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones(3)  ##Creates an array full of ones

array([1., 1., 1.])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.empty( (2,3) ) #Creates an array whose initial content is random and depends on the state of the memory.

array([[0., 0., 0.],
       [0., 0., 0.]])

#### To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.arange(1,10,2) #(lb,ub+1,step)
a

array([1, 3, 5, 7, 9])

#### When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained,

#### For this reason, it is usually better to use the function linspace

In [42]:
np.linspace( 0, 2, 9 )  #(lb,ub,no_of_elements)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners

In [49]:
a = np.arange(10000)


#### To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

#### np.set_printoptions(threshold=np.nan)

### BASIC OPERATIONS

In [63]:
a = np.array([[1,2],
             [4,5]])
b = np.array([[9,8],
             [6,5]])


In [64]:
c = a * b     # element wise product
c

array([[ 9, 16],
       [24, 25]])

In [65]:
a @ b        # matrix product 1

array([[21, 18],
       [66, 57]])

In [ ]:
a.dot(b)     # matrix product 2

In [76]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a



array([[3, 3, 3],
       [3, 3, 3]])

In [75]:
b += a
b

array([[3.7180318 , 3.36435398, 3.08432585],
       [3.82556312, 3.39883741, 3.15646165]])

In [78]:
a += b   # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [81]:
a = np.random.random((2,3))
a.sum()



3.0307125108033244

In [82]:
a.min()

0.016929431424595354

In [83]:
a.max()

0.9331581996268662

In [98]:
a = np.random.randint(1,10,9).reshape(3,3)
a

array([[6, 3, 5],
       [9, 1, 6],
       [9, 4, 1]])

#### By specifying the axis parameter you can apply an operation along the specified axis of an array:


In [99]:
a.min(axis = 0)    #column wise min value

array([6, 1, 1])

In [102]:
a.sum(axis = 1)   #row wise sum

array([14, 16, 14])

# INDEXING, SLICING, ITERATING

In [110]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [104]:
a[2]    #index

8

In [105]:
a[2:5]   #slicing

array([ 8, 27, 64], dtype=int32)

In [113]:
a[:6:2] = 100    # equivalent to a[0:6:2] = 100; from start to position 6, exclusive, set every 2nd element to -1000
a

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729], dtype=int32)

In [114]:
a[ : :-1] # reversed a

array([729, 512, 343, 216, 125, 100,  27, 100,   1, 100], dtype=int32)

In [115]:
for i in a:
    print(i**(1/3))

4.641588833612778
1.0
4.641588833612778
3.0
4.641588833612778
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [116]:
a = np.arange(20).reshape(5,4)

In [117]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [118]:
a[2,3]    # 2nd index row, 3rd index column

11

In [119]:
a[:5, 1]    #(r_lb : r_ub+1 , c_lb : c_ub+1)                   # each row in the second column of b

array([ 1,  5,  9, 13, 17])

In [120]:
a[2,:]

array([ 8,  9, 10, 11])

In [133]:
a[::-1]             # reverse a matrix

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [125]:
a[-3:-1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 3D ARRAY

In [134]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [135]:
c[1,...]                 # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [136]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

#### If one wants to perform an operation on each element in the array, one can use the flat attribute

In [138]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [146]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


# SHAPE MANIPULATION

In [149]:
a = np.random.randint(1,10,20).reshape(5,4)
a

array([[1, 9, 8, 2],
       [1, 1, 1, 8],
       [7, 2, 4, 6],
       [2, 5, 1, 8],
       [4, 8, 4, 6]])

In [150]:
a.ravel()    # returns the array, flattened

array([1, 9, 8, 2, 1, 1, 1, 8, 7, 2, 4, 6, 2, 5, 1, 8, 4, 8, 4, 6])

In [152]:
a.T     # Transpose of an array

array([[1, 1, 7, 2, 4],
       [9, 1, 2, 5, 8],
       [8, 1, 4, 1, 4],
       [2, 8, 6, 8, 6]])

#### If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated

In [156]:
a.reshape(5,-1)   

array([[1, 9, 8, 2],
       [1, 1, 1, 8],
       [7, 2, 4, 6],
       [2, 5, 1, 8],
       [4, 8, 4, 6]])

In [170]:
a = np.random.randint(1,10,20).reshape(5,4)
a

array([[4, 9, 8, 6],
       [6, 7, 9, 3],
       [6, 3, 6, 1],
       [9, 8, 1, 5],
       [4, 7, 9, 5]])

In [174]:
a.resize(4,5)
a

array([[4, 9, 8, 6, 6],
       [7, 9, 3, 6, 3],
       [6, 1, 9, 8, 1],
       [5, 4, 7, 9, 5]])

#### The reshape function returns its argument with a modified shape, whereas the resize method modifies the array itself

### Stacking

In [181]:
a = np.random.randint(1,10,9).reshape(3,3)
a

array([[5, 2, 3],
       [9, 1, 8],
       [2, 3, 6]])

In [182]:
b = np.random.randint(1,10,9).reshape(3,3)
b

array([[6, 5, 5],
       [3, 6, 9],
       [3, 9, 3]])

In [184]:
np.hstack((a,b))     # Horizontal stack

array([[5, 2, 3, 6, 5, 5],
       [9, 1, 8, 3, 6, 9],
       [2, 3, 6, 3, 9, 3]])

In [185]:
np.vstack((a,b))      # Vertical Stack

array([[5, 2, 3],
       [9, 1, 8],
       [2, 3, 6],
       [6, 5, 5],
       [3, 6, 9],
       [3, 9, 3]])

In [187]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#### The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays

In [188]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

#### In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis

In [191]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

### Splitting

In [204]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [205]:
np.hsplit(a,3)          #Using hsplit, you can split an array along its horizontal axis; split into 3

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [209]:
np.hsplit(a,(3,4))                 # Split a after the third and the fourth column

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [210]:
np.vsplit(a,3)                    #Using hsplit, you can split an array along its vertical axis

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

## Miscellaneous

### You can also use indexing with arrays as a target to assign to

### However, when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value

In [212]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [213]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [214]:
a = np.arange(5)                        #With repititions
a[[0,0,2]]=[1,2,3]
a


array([2, 1, 3, 3, 4])